# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Travello"
license = "MIT"
licenselink = "https://github.com/xs4free/hugo-travello-theme/blob/master/LICENSE"
description = ""
homepage = "https://github.com/xs4free/hugo-travello-theme"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Rogier Reedijk"
  homepage = "https://github.com/xs4free"

# If porting an existing theme
[original]
  name = "blog theme from Bootstrap"
  homepage = "https://getbootstrap.com/docs/4.1/examples/blog/"
  repo = "https://github.com/twbs/bootstrap/tree/v4-dev/site/docs/4.1/examples/blog"
